stages:
    - build
before_script:
  - 'C:\Nuget\nuget.exe restore TesteMVC.csproj'
job:
    stage: build
    script: '"C:\Program Files (x86)\MSBuild\15.0\Bin\MSBuild.exe" "TesteMVC.csproj"'

image : microsoft/dotnet:latest
stages:
  - build
before_script:
  - 'dotnet restore'
build:
 stage: build
 script:
  - 'dotnet build'
 only:
   - master